#goal definition
---
#result definition
geometry_msgs/PoseStamped table_pose
geometry_msgs/PointStamped p1
geometry_msgs/PointStamped p2
geometry_msgs/PointStamped p3
geometry_msgs/PointStamped p4
geometry_msgs/PointCloud[] objects
---
#feedback